/** Exam / class targets collected during onboarding. */
export const CLASS_OR_TARGETS = [
  { value: "class-6-8", label: "Class 6–8" },
  { value: "class-9-10", label: "Class 9–10 (Boards)" },
  { value: "class-11-12", label: "Class 11–12" },
  { value: "ibps-clerk", label: "IBPS Clerk" },
  { value: "ibps-po", label: "IBPS PO" },
  { value: "sbi-po", label: "SBI PO" },
  { value: "ssc-cgl", label: "SSC CGL" },
  { value: "ssc-chsl", label: "SSC CHSL" },
  { value: "general-aptitude", label: "General aptitude" },
] as const;

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Puducherry",
  "Chandigarh",
] as const;
