import type { ApiResult } from "@/types/common";
import type { DbAccess, JsonRow, ListQuery, ListResult } from "@/database/types";
import {
  findById,
  listRows,
  insertRow,
  updateRow,
  deleteRow,
  resolveClient
} from "@/database/baseRepository";
import { runListQuery, runQuery } from "@/database/supabaseClient";

const TABLE = "hh_duties";
const SVC = "hh_svc_entries";
const PAYOUT_CHARGES = "hh_payout_charges";
const RECEIPTS = "hh_receipts";
const SCOPE = "dutyRepository";

export interface DutyListFilters extends ListQuery {
  q?: string;
  employeeId?: string;
  patientId?: string;
  from?: string;
  to?: string;
  status?: string;
}

export const dutyRepository = {
  findById(id: string, opts?: DbAccess): Promise<ApiResult<JsonRow | null>> {
    return findById(TABLE, id, SCOPE, opts);
  },

  list(filters: DutyListFilters = {}, opts?: DbAccess): Promise<ApiResult<ListResult<JsonRow>>> {
    return listRows(
      TABLE,
      SCOPE,
      (q) => {
        let query = q;
        if (filters.employeeId) query = query.eq("employee_id", filters.employeeId);
        if (filters.patientId) query = query.eq("patient_id", filters.patientId);
        if (filters.from) query = query.gte("start_at", filters.from);
        if (filters.to) query = query.lte("end_at", filters.to);
        if (filters.status) query = query.eq("status", filters.status);
        if (filters.q) {
          const term = filters.q.replace(/%/g, "");
          query = query.or(
            ["service_type", "shift_type", "status", "notes"]
              .map((c) => `${c}.ilike.%${term}%`)
              .join(",")
          );
        }
        return query;
      },
      { ...opts, ...filters, orderBy: filters.orderBy ?? "start_at", ascending: filters.ascending ?? false }
    );
  },

  /** Overlapping duties for same employee (excludes CANCELLED / NO_SHOW). */
  async findOverlapping(
    employeeId: string,
    startAt: string,
    endAt: string,
    excludeId?: string,
    opts?: DbAccess
  ): Promise<ApiResult<JsonRow[]>> {
    const db = resolveClient(opts);
    const result = await runListQuery(
      () =>
        db
          .from(TABLE)
          .select("id, employee_id, patient_id, start_at, end_at, status")
          .eq("employee_id", employeeId)
          .not("status", "in", "(CANCELLED,NO_SHOW)")
          .lt("start_at", endAt)
          .gt("end_at", startAt),
      `${SCOPE}.findOverlapping`
    );
    if (!result.success) return result;
    const rows = (result.data || []).filter((r) => !excludeId || String(r.id) !== excludeId);
    return { success: true, data: rows };
  },

  /** Overlapping duties for same patient (excludes CANCELLED / NO_SHOW). */
  async findOverlappingForPatient(
    patientId: string,
    startAt: string,
    endAt: string,
    excludeId?: string,
    opts?: DbAccess
  ): Promise<ApiResult<JsonRow[]>> {
    const db = resolveClient(opts);
    const result = await runListQuery(
      () =>
        db
          .from(TABLE)
          .select("id, employee_id, patient_id, start_at, end_at, status")
          .eq("patient_id", patientId)
          .not("status", "in", "(CANCELLED,NO_SHOW)")
          .lt("start_at", endAt)
          .gt("end_at", startAt),
      `${SCOPE}.findOverlappingForPatient`
    );
    if (!result.success) return result;
    const rows = (result.data || []).filter((r) => !excludeId || String(r.id) !== excludeId);
    return { success: true, data: rows };
  },

  insert(row: JsonRow, opts?: DbAccess): Promise<ApiResult<JsonRow | null>> {
    return insertRow(TABLE, row, SCOPE, opts);
  },

  update(id: string, patch: JsonRow, opts?: DbAccess): Promise<ApiResult<JsonRow | null>> {
    return updateRow(TABLE, id, patch, SCOPE, opts);
  },

  remove(id: string, opts?: DbAccess): Promise<ApiResult<null>> {
    return deleteRow(TABLE, id, SCOPE, opts);
  },

  /** Service-entry rows generated by a given duty within its billing record. */
  async findSvcEntriesForDuty(
    billingId: string,
    dutyId: string,
    opts?: DbAccess
  ): Promise<ApiResult<JsonRow[]>> {
    const db = resolveClient(opts);
    return runListQuery(
      () =>
        db
          .from(SVC)
          .select("id, billing_id, remarks")
          .eq("billing_id", billingId)
          .eq("remarks", `duty:${dutyId}`),
      `${SCOPE}.findSvcEntriesForDuty`
    );
  },

  /** Remove the service-entry rows generated by a duty (safe billing rollback). */
  async removeSvcEntriesForDuty(
    billingId: string,
    dutyId: string,
    opts?: DbAccess
  ): Promise<ApiResult<null>> {
    const db = resolveClient(opts);
    return runQuery<null>(
      () =>
        db
          .from(SVC)
          .delete()
          .eq("billing_id", billingId)
          .eq("remarks", `duty:${dutyId}`)
          .then(({ error }) => ({ data: null, error })),
      `${SCOPE}.removeSvcEntriesForDuty`
    );
  },

  /** All svc rows materialized from a duty (`duty:<id>:...` remarks). */
  async findSvcEntriesByDutyId(dutyId: string, opts?: DbAccess): Promise<ApiResult<JsonRow[]>> {
    const db = resolveClient(opts);
    return runListQuery(
      () =>
        db
          .from(SVC)
          .select("id, billing_id, svc_key, date, partner_id, remarks, total")
          .like("remarks", `duty:${dutyId}:%`),
      `${SCOPE}.findSvcEntriesByDutyId`
    );
  },

  async removeSvcEntriesByDutyId(dutyId: string, opts?: DbAccess): Promise<ApiResult<null>> {
    const db = resolveClient(opts);
    return runQuery<null>(
      () =>
        db
          .from(SVC)
          .delete()
          .like("remarks", `duty:${dutyId}:%`)
          .then(({ error }) => ({ data: null, error })),
      `${SCOPE}.removeSvcEntriesByDutyId`
    );
  },

  async findPayoutChargesByDutyId(dutyId: string, opts?: DbAccess): Promise<ApiResult<JsonRow[]>> {
    const db = resolveClient(opts);
    return runListQuery(
      () =>
        db
          .from(PAYOUT_CHARGES)
          .select("id, svc_key, date, partner_id, amount, remarks")
          .like("remarks", `duty:${dutyId}:%`),
      `${SCOPE}.findPayoutChargesByDutyId`
    );
  },

  async removePayoutChargesByDutyId(dutyId: string, opts?: DbAccess): Promise<ApiResult<null>> {
    const db = resolveClient(opts);
    return runQuery<null>(
      () =>
        db
          .from(PAYOUT_CHARGES)
          .delete()
          .like("remarks", `duty:${dutyId}:%`)
          .then(({ error }) => ({ data: null, error })),
      `${SCOPE}.removePayoutChargesByDutyId`
    );
  },

  /** Count live (non-deleted) receipts attached to a billing. */
  async countActiveReceipts(billingId: string, opts?: DbAccess): Promise<ApiResult<number>> {
    const db = resolveClient(opts);
    const result = await runListQuery<JsonRow>(
      () =>
        db
          .from(RECEIPTS)
          .select("id")
          .eq("billing_id", billingId)
          .is("deleted_at", null),
      `${SCOPE}.countActiveReceipts`
    );
    if (!result.success) {
      return { success: false, error: result.error, code: result.code, details: result.details };
    }
    return { success: true, data: (result.data || []).length };
  }
};
