-- Per-period invoices: a patient now has ONE bill account but MANY invoices.
-- Each generated invoice (monthly or manual) gets its own invoice_no and starts
-- UNPAID; receipts are recorded against a specific invoice.
--
-- Tables added:
--   - hh_invoices       (one row per invoice generation)
--   - hh_invoice_lines  (snapshot of svc entries that produced the invoice)
-- Columns added:
--   - hh_receipts.invoice_id  (optional link)
--
-- We KEEP hh_billings.invoice_no / paid_status from migration 037 for
-- back-compat but the UI no longer surfaces them — the bill is the patient
-- account, the invoice is the document.

create table if not exists public.hh_invoices (
  id text primary key,
  invoice_no text not null,
  billing_id text not null references public.hh_billings(id) on delete cascade,
  patient_id text not null,
  kind text not null default 'MONTHLY',
  period text,
  from_date date,
  to_date date,
  amount numeric(12,2) not null default 0,
  status text not null default 'UNPAID',
  notes text default '',
  created_by text default '',
  updated_by text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_hh_invoices_invoice_no on public.hh_invoices (invoice_no);
create index if not exists hh_invoices_billing_id_idx on public.hh_invoices (billing_id);
create index if not exists hh_invoices_patient_id_idx on public.hh_invoices (patient_id);

alter table public.hh_invoices
  drop constraint if exists chk_hh_invoices_status;
alter table public.hh_invoices
  add constraint chk_hh_invoices_status
  check (status in ('UNPAID', 'PARTIAL', 'PAID', 'CANCELLED'));

alter table public.hh_invoices
  drop constraint if exists chk_hh_invoices_kind;
alter table public.hh_invoices
  add constraint chk_hh_invoices_kind
  check (kind in ('MONTHLY', 'MANUAL'));

create table if not exists public.hh_invoice_lines (
  id bigint generated by default as identity primary key,
  invoice_id text not null references public.hh_invoices(id) on delete cascade,
  svc_entry_id bigint,
  date text default '',
  service_name text default '',
  partner text default '',
  count numeric not null default 1,
  amt numeric not null default 0,
  total numeric not null default 0
);
create index if not exists hh_invoice_lines_invoice_idx on public.hh_invoice_lines (invoice_id);

alter table public.hh_receipts
  add column if not exists invoice_id text;
create index if not exists hh_receipts_invoice_id_idx on public.hh_receipts (invoice_id);

-- updated_at trigger (shared helper from earlier migrations)
do $$
begin
  if to_regprocedure('public.hh_set_updated_at()') is not null then
    drop trigger if exists hh_invoices_updated_at on public.hh_invoices;
    create trigger hh_invoices_updated_at before update on public.hh_invoices
      for each row execute function public.hh_set_updated_at();
  end if;
end $$;

-- RLS
alter table public.hh_invoices enable row level security;
alter table public.hh_invoice_lines enable row level security;

do $$
begin
  if to_regprocedure('public.hh_is_active_app_user()') is not null then
    drop policy if exists hh_invoices_authenticated_access on public.hh_invoices;
    create policy hh_invoices_authenticated_access on public.hh_invoices
      for all to authenticated
      using (public.hh_is_active_app_user())
      with check (public.hh_is_active_app_user());

    drop policy if exists hh_invoice_lines_authenticated_access on public.hh_invoice_lines;
    create policy hh_invoice_lines_authenticated_access on public.hh_invoice_lines
      for all to authenticated
      using (public.hh_is_active_app_user())
      with check (public.hh_is_active_app_user());
  end if;
end $$;

-- Realtime (best-effort)
alter table if exists public.hh_invoices replica identity full;
alter table if exists public.hh_invoice_lines replica identity full;

do $$
begin
  begin
    execute 'alter publication supabase_realtime add table public.hh_invoices';
  exception when duplicate_object then null; when undefined_object then null;
  end;
  begin
    execute 'alter publication supabase_realtime add table public.hh_invoice_lines';
  exception when duplicate_object then null; when undefined_object then null;
  end;
end $$;
