import { buildEmployeePermissions } from "@/business/employeeRules";

/** Canonical EmployeeDetailDTO fixture for contract tests. */
export function employeeDetailFixture(overrides: Record<string, unknown> = {}) {
  const status = String((overrides.status as string | undefined) || "Active");
  return {
    id: "EMP2026050001",
    full_name: "Test Employee",
    name: "Test Employee",
    fn: "Test",
    mn: "",
    ln: "Employee",
    phone: "9999999999",
    mobile: "9999999999",
    email: "",
    phone2: "",
    gender: "Male",
    dob: "1985-01-15",
    blood: "O+",
    area: "Ahmedabad",
    permaddr: "1 Test Lane",
    presaddr: "1 Test Lane",
    addr: "1 Test Lane",
    address: "1 Test Lane",
    pin: "380001",
    pincode: "380001",
    district: "Ahmedabad",
    state: "Gujarat",
    aadhar: "123456789012",
    pan: "ABCDE1234F",
    dept: "Care",
    department: "Care",
    designation: "Caretaker",
    desig: "Caretaker",
    role: "Caretaker",
    employee_type: "FullTime",
    emp_type: "FullTime",
    etype: "FullTime",
    education: "B.Sc.",
    edu: "B.Sc.",
    exp: "5",
    company: "",
    shift: "DAY",
    shift_type: "DAY",
    salary: 25000,
    join_date: "2026-01-01",
    leave_date: null,
    status,
    active: status === "Active",
    ecname: "Kin",
    ecphone: "9888888888",
    ecrel: "Spouse",
    relname: "Kin",
    relphone: "9888888888",
    skills: "",
    docs: [],
    employee_documents: [],
    photo: null,
    score_experience: null,
    score_behaviour: null,
    score_testimonial: null,
    score_total: null,
    created_at: "2026-05-01T05:00:00.000Z",
    updated_at: "2026-05-01T05:00:00.000Z",
    permissions: buildEmployeePermissions({ status }),
    ...overrides
  };
}
